--local LocalLibStub, NewLocalLibrary, M = ABP_LibGlobals:LibPack()
--local unpack, format = unpack, string.format
--
--local _L = NewLocalLibrary(M.AceUtil, 1)
--
---- ## Start Here ## --
--
--local libAceConsole
--
--function _L.LocalLibStub(localLibName) return LocalLibStub(localLibName) end
--
--function _L:NewLibrary(libName)
--    local version = self:GetAceLibVersion(libName)
--    local newLib = LibStub:NewLibrary(unpack(version))
--    newLib.__name = libName
--    return newLib
--end
--
--function _L:GetAceConsole()
--    libAceConsole = self:LazyGetAceLib(libAceConsole, AceModule.AceConsole)
--    return libAceConsole
--end
--
--function _L:LazyGetAceLib(libObj, libName)
--    if not libObj then return LibStub(libName) end
--    return libObj
--end
