--[[

    Please do NOT edit this file.
    The contents of this file will be generated automatically.
    
]]--

---@class Localization
local L = LibStub("AceLocale-3.0"):NewLocale("ActionbarPlus", "enUS", true);

for bar = 1,8,1
do
    for button = 1,20,1
    do
        -- Example: L["BINDING_NAME_ABP_ACTIONBAR1_BUTTON1"]  = 'Bar #1 Action Button 1'
        local left = string.format('BINDING_NAME_ABP_ACTIONBAR%s_BUTTON%s', bar, button)
        local right = string.format('Bar #%s Action Button %s', bar, button)
        L[left] = right
    end
end

L['ABP_GENERAL_CONFIG_LOCK_ACTION_BARS_NAME']  = 'Lock Actionbars with SHIFT key'
L['ABP_GENERAL_CONFIG_LOCK_ACTION_BARS_DESC']  = 'Prevents user from picking up or dragging spells, items, or macros from the ActionbarPlus bars.'
L['ABP_GENERAL_CONFIG_HIDE_WHEN_TAXI_ACTION_BARS_NAME']  = 'Hide Actionbars while in taxi'
L['ABP_GENERAL_CONFIG_HIDE_WHEN_TAXI_ACTION_BARS_DESC']  = 'Hides the action bars while the player is in taxi; flying from one point to another.'
