--[[
    Please do NOT edit this file.
    The contents of this file will be generated automatically.
]]--

local addon = ...

local L = LibStub("AceLocale-3.0"):NewLocale(addon, "esES", true);
if not L then return end

--[[-----------------------------------------------------------------------------
Localization Keys
-------------------------------------------------------------------------------]]

--@localization(locale="esES", format="lua_additive_table", handle-subnamespaces="concat")@
