--[[
    Please do NOT edit this file.
    The contents of this file will be generated automatically.
]]--

--[[-----------------------------------------------------------------------------
Lua Vars
-------------------------------------------------------------------------------]]
local sformat = string.format
local addon = ...

local L = LibStub("AceLocale-3.0"):NewLocale(addon, "esMX", true);
if not L then return end

--[[-----------------------------------------------------------------------------
Keybinding Localization
-------------------------------------------------------------------------------]]
ABP_BUTTON_NAME_TEXT_FORMAT_DEFAULT         = 'Barra de acciones #%s Botón %s'

for bar = 1,8,1
do
    for button = 1,50,1
    do
        -- Example: L["BINDING_NAME_ABP_ACTIONBAR1_BUTTON1"]  = 'Bar #1 Action Button 1'
        local left = sformat('BINDING_NAME_ABP_ACTIONBAR%s_BUTTON%s', bar, button)
        local right = sformat(ABP_BUTTON_NAME_TEXT_FORMAT_DEFAULT, bar, button)
        L[left] = right
    end
end

--[[-----------------------------------------------------------------------------
Localization Keys
-------------------------------------------------------------------------------]]

--@localization(locale="esES", format="lua_additive_table", handle-subnamespaces="concat")@
